image: archlinux
submitter:
  git.sr.ht:
    enabled: true
    allow-refs:
      - refs/head/main
      - "refs/tags/*"
packages:
  - zig
sources:
  - https://git.sr.ht/~gary_moore/simple-image-printer
artifacts:
  - simple-image-printer/zig-out/bin/icat
tasks:
  - build: |
      cd simple-image-printer
      zig build --summary all -Dtarget=x86_64-linux -Dcpu=x86_64_v3 --release=fast
      strip zig-out/bin/icat
